### ISSUE TITLE
add git-commit icon

### ISSUE THREAD

**Issue by jhamman** [carbonplan/icons#2]
something like: 
![image](https://user-images.githubusercontent.com/2443309/134611658-77657d65-c2dc-42e6-8e9e-75d7edf239d6.png)

**Comment by jhamman** [comment]
xref: https://github.com/carbonplan/components/pull/96

**Comment by freeman-lab** [comment]
Given that we resolved the referenced PR with another approach, this is probably no longer needed. Definitely seems possible we'll want one or more GitHub related icons in the future though! Maybe we can wait till we need it, and close this for now? Or, I can open a separate issue with "wanted icons" list?

**Comment by jhamman** [comment]
I think we can close this for now. Easy to reopen when there is a use case.
